"""
Deep-convolutional control-baseline encoder (Stage 2 arm E1): the 16-layer octave/gated-DSC
geometry of the CVPRW 2024 reference system, re-implemented as a COMPARISON BASELINE. It is not
a HAND architecture component.

Source of truth: Castro, Bezerra & Zanchettin, "An End-to-End Approach for Handwriting
Recognition: From Handwritten Text Lines to Complete Pages", CVPR 2024 Workshops (LXCV),
**and its supplementary material, Table SI 1**, which is the only place the layer-by-layer
hyper-parameters appear:

    Block        Config          Values
    ------------------------------------------------------------------
    Vanilla      filters         16 - 16 - 16
                 stride          1x1 - 1x1 - 1x1
    Octave       filters         32 - 32 - 64 - 64 - 128 - 128 - 128 - 128 - 128 - 128
                 octave alpha    0.500 - 0.500 - 0.375 - 0.375 - 0.250 - 0.250 -
                                 0.125 - 0.125 - 0.125 - 0.000
                 stride          1x1 - 2x2 - 1x1 - 2x2 - 1x1 - 2x2 - 1x1 - 1x1 - 1x1 - 1x1
                 max pool        0x0 x7 - 2x1 - 0x0 - 2x1
    DW-separable filters         256 - 256 - 256
                 gated conv      No - No - Yes
                 stride          1x1 - 1x1 - 1x1

Main text: the vanilla block is "three traditional convolution layers plus an instance
normalization layer"; the five octave blocks each hold "two octave convolution layers followed
by an instance normalization layer"; the last block is "three highly efficient depth-wise
separable conv layers" with "a gated convolution in the depth-wise portion of the last layer";
Diffused Mix Dropout (0.5 standard / 0.25 spatial) is placed at a randomly chosen position
inside each block. 3 + 10 + 3 = 16 layers, plus the extra gated convolution.

Geometry: strides 2x2 at octave layers 2, 4 and 6 give H/8 x W/8; the two 2x1 max pools at
layers 8 and 10 take the height to H/32. Output is therefore (B, 256, H/32, W/8) — identical to
`FCN_Encoder`, so the DAN/HAND decoder is untouched.

This is a NEW implementation. It deliberately shares nothing with the failed five-block HAND
octave encoder that Experiment 2 rejected (`docs/ablations.md` section 1.1), whose two
defects are excluded by construction here:
  * the low-frequency path is never silently disabled — pooling uses `ceil_mode=True` and the
    upsample restores the *measured* high-path size, so any input height works;
  * restoration is **bilinear**, not nearest-neighbour.
"""
import random

import torch
import torch.nn.functional as F
from torch.nn import Conv2d, InstanceNorm2d, Module, ModuleList, ReLU, Sigmoid

from hand.models.baseline.fcn_encoder import DepthSepConv2D, MixDropout

# Table SI 1, in layer order.
OCTAVE_FILTERS = (32, 32, 64, 64, 128, 128, 128, 128, 128, 128)
OCTAVE_ALPHA = (0.500, 0.500, 0.375, 0.375, 0.250, 0.250, 0.125, 0.125, 0.125, 0.000)
OCTAVE_STRIDE = ((1, 1), (2, 2), (1, 1), (2, 2), (1, 1), (2, 2), (1, 1), (1, 1), (1, 1), (1, 1))
OCTAVE_POOL = (None, None, None, None, None, None, None, (2, 1), None, (2, 1))
VANILLA_FILTERS = (16, 16, 16)
DSC_FILTERS = (256, 256, 256)


def _split(channels, alpha):
    """Channel split of an octave tensor: (high, low)."""
    low = int(round(alpha * channels))
    return channels - low, low


class GatedDepthSepConv2D(Module):
    """Depth-wise separable convolution whose depth-wise part is gated.

    The gate is a second sigmoid-activated depth-wise convolution multiplied element-wise with
    the depth-wise output ("the gated conv operates by applying an element-wise multiplication
    of the convolution output with a gating signal ... generated by another sigmoid-activated
    convolution"), followed by the usual point-wise projection.

    The paper says only "a gated convolution [15] in the depth-wise portion of the last layer",
    without stating whether the *gating* convolution is itself depth-wise. Parameter accounting
    decides it: with a full 3x3 gate (256x256x9 = 590 K) the encoder reaches 1.65 M and the whole
    model 6.98 M against DANCER's published 6.93 M (0.7 % off); with a depth-wise gate (2.3 K)
    the model would be 6.39 M (8 % off). `gate_mode="full"` is therefore the default, and
    `gate_mode="depthwise"` is kept so the alternative reading can be ablated.
    """

    def __init__(self, in_channels, out_channels, kernel_size=(3, 3), stride=(1, 1),
                 gate_mode="full"):
        super().__init__()
        padding = (kernel_size[0] // 2, kernel_size[1] // 2)
        self.depth_conv = Conv2d(in_channels, in_channels, kernel_size, stride=stride,
                                 padding=padding, groups=in_channels)
        self.gate_conv = Conv2d(in_channels, in_channels, kernel_size, stride=stride,
                                padding=padding,
                                groups=in_channels if gate_mode == "depthwise" else 1)
        self.gate_act = Sigmoid()
        self.point_conv = Conv2d(in_channels, out_channels, kernel_size=(1, 1))

    def forward(self, x):
        return self.point_conv(self.depth_conv(x) * self.gate_act(self.gate_conv(x)))


class OctaveConv2d(Module):
    """Octave convolution (Chen et al., ICCV 2019) with an explicit low-frequency ratio.

    Y_H = conv_hh(X_H) + up(conv_lh(X_L))
    Y_L = conv_hl(pool(X_H)) + conv_ll(X_L)

    `alpha_in == 0` accepts a plain tensor; `alpha_out == 0` returns a plain tensor. Strides > 1
    are applied by average-pooling the inputs first, which keeps the two paths in step.
    """

    def __init__(self, in_channels, out_channels, alpha_in, alpha_out,
                 kernel_size=(3, 3), stride=(1, 1)):
        super().__init__()
        self.alpha_in, self.alpha_out, self.stride = alpha_in, alpha_out, tuple(stride)
        in_h, in_l = _split(in_channels, alpha_in)
        out_h, out_l = _split(out_channels, alpha_out)
        self.in_h, self.in_l, self.out_h, self.out_l = in_h, in_l, out_h, out_l
        padding = (kernel_size[0] // 2, kernel_size[1] // 2)

        self.conv_hh = Conv2d(in_h, out_h, kernel_size, padding=padding) if in_h and out_h else None
        self.conv_hl = Conv2d(in_h, out_l, kernel_size, padding=padding) if in_h and out_l else None
        self.conv_lh = Conv2d(in_l, out_h, kernel_size, padding=padding) if in_l and out_h else None
        self.conv_ll = Conv2d(in_l, out_l, kernel_size, padding=padding) if in_l and out_l else None

    def forward(self, x):
        x_h, x_l = x if isinstance(x, tuple) else (x, None)
        if self.stride != (1, 1):
            x_h = F.avg_pool2d(x_h, kernel_size=self.stride, stride=self.stride, ceil_mode=True)
            if x_l is not None:
                x_l = F.avg_pool2d(x_l, kernel_size=self.stride, stride=self.stride, ceil_mode=True)

        y_h = self.conv_hh(x_h) if self.conv_hh is not None else None
        # high -> low: the low path lives at half resolution; ceil_mode keeps H=1 legal
        x_h_pooled = F.avg_pool2d(x_h, kernel_size=2, stride=2, ceil_mode=True) if self.conv_hl is not None else None
        y_l = self.conv_hl(x_h_pooled) if self.conv_hl is not None else None

        if x_l is not None:
            if self.conv_lh is not None:
                # bilinear restoration to the measured high-path size (never nearest, never assumed)
                up = F.interpolate(self.conv_lh(x_l), size=y_h.shape[-2:],
                                   mode="bilinear", align_corners=False)
                y_h = up if y_h is None else y_h + up
            if self.conv_ll is not None:
                ll = self.conv_ll(x_l)
                if y_l is None:
                    y_l = ll
                else:
                    if ll.shape[-2:] != y_l.shape[-2:]:
                        ll = F.interpolate(ll, size=y_l.shape[-2:], mode="bilinear", align_corners=False)
                    y_l = y_l + ll
        return y_h if self.alpha_out == 0 else (y_h, y_l)


def _act(x, act):
    return (act(x[0]), act(x[1])) if isinstance(x, tuple) else act(x)


def _norm(x, norm_h, norm_l):
    return (norm_h(x[0]), norm_l(x[1])) if isinstance(x, tuple) else norm_h(x)


def _drop(x, dropout):
    return (dropout(x[0]), dropout(x[1])) if isinstance(x, tuple) else dropout(x)


class VanillaBlock(Module):
    """Three plain 3x3 convolutions + instance norm, Diffused Mix Dropout at a random position."""

    def __init__(self, in_channels, filters, dropout=0.5):
        super().__init__()
        self.activation = ReLU()
        c1, c2, c3 = filters
        self.conv1 = Conv2d(in_channels, c1, (3, 3), padding=1)
        self.conv2 = Conv2d(c1, c2, (3, 3), padding=1)
        self.conv3 = Conv2d(c2, c3, (3, 3), padding=1)
        self.norm = InstanceNorm2d(c3, eps=0.001, momentum=0.99, track_running_stats=False)
        self.dropout = MixDropout(dropout_proba=dropout, dropout2d_proba=dropout / 2)

    def forward(self, x):
        pos = random.randint(1, 3)
        x = self.activation(self.conv1(x))
        if pos == 1:
            x = self.dropout(x)
        x = self.activation(self.conv2(x))
        if pos == 2:
            x = self.dropout(x)
        x = self.activation(self.conv3(x))
        if pos == 3:
            x = self.dropout(x)
        return self.norm(x)


class OctaveBlock(Module):
    """Two octave convolutions + instance norm; dropout before conv2, before or after the norm."""

    def __init__(self, in_channels, alpha_in, idx_a, idx_b, dropout=0.5):
        super().__init__()
        self.activation = ReLU()
        self.conv_a = OctaveConv2d(in_channels, OCTAVE_FILTERS[idx_a], alpha_in,
                                   OCTAVE_ALPHA[idx_a], stride=OCTAVE_STRIDE[idx_a])
        self.conv_b = OctaveConv2d(OCTAVE_FILTERS[idx_a], OCTAVE_FILTERS[idx_b],
                                   OCTAVE_ALPHA[idx_a], OCTAVE_ALPHA[idx_b],
                                   stride=OCTAVE_STRIDE[idx_b])
        self.pool_a, self.pool_b = OCTAVE_POOL[idx_a], OCTAVE_POOL[idx_b]
        out_h, out_l = _split(OCTAVE_FILTERS[idx_b], OCTAVE_ALPHA[idx_b])
        self.norm_h = InstanceNorm2d(out_h, eps=0.001, momentum=0.99, track_running_stats=False)
        self.norm_l = (InstanceNorm2d(out_l, eps=0.001, momentum=0.99, track_running_stats=False)
                       if out_l else None)
        self.dropout = MixDropout(dropout_proba=dropout, dropout2d_proba=dropout / 2)
        self.alpha_out = OCTAVE_ALPHA[idx_b]

    @staticmethod
    def _pool(x, pool):
        if pool is None:
            return x
        if isinstance(x, tuple):
            return (F.max_pool2d(x[0], pool, pool, ceil_mode=True),
                    F.max_pool2d(x[1], pool, pool, ceil_mode=True) if x[1] is not None else None)
        return F.max_pool2d(x, pool, pool, ceil_mode=True)

    def forward(self, x):
        pos = random.randint(1, 3)
        x = _act(self.conv_a(x), self.activation)
        x = self._pool(x, self.pool_a)
        if pos == 1:
            x = _drop(x, self.dropout)
        x = _act(self.conv_b(x), self.activation)
        x = self._pool(x, self.pool_b)
        if pos == 2:
            x = _drop(x, self.dropout)
        x = _norm(x, self.norm_h, self.norm_l)
        if pos == 3:
            x = _drop(x, self.dropout)
        return x


class DSCBlockGated(Module):
    """Three depth-wise separable convolutions; the last one's depth-wise part is gated."""

    def __init__(self, in_channels, filters, dropout=0.5, gate_mode="full"):
        super().__init__()
        self.activation = ReLU()
        c1, c2, c3 = filters
        self.conv1 = DepthSepConv2D(in_channels, c1, kernel_size=(3, 3))
        self.conv2 = DepthSepConv2D(c1, c2, kernel_size=(3, 3))
        self.conv3 = GatedDepthSepConv2D(c2, c3, kernel_size=(3, 3), gate_mode=gate_mode)
        self.norm = InstanceNorm2d(c3, eps=0.001, momentum=0.99, track_running_stats=False)
        self.dropout = MixDropout(dropout_proba=dropout, dropout2d_proba=dropout / 2)

    def forward(self, x):
        pos = random.randint(1, 3)
        x = self.activation(self.conv1(x))
        if pos == 1:
            x = self.dropout(x)
        x = self.activation(self.conv2(x))
        if pos == 2:
            x = self.dropout(x)
        x = self.activation(self.conv3(x))
        if pos == 3:
            x = self.dropout(x)
        return self.norm(x)


class DANCER_Encoder(Module):
    """DANCER's encoder: 3 vanilla + 10 octave + 3 depth-wise separable (last gated) layers.

    Interface-compatible with `FCN_Encoder`: constructed from the same `params` dict and
    returning (B, 256, H/32, W/8).
    """

    def __init__(self, params):
        super().__init__()
        dropout = params.get("dropout", 0.5)
        in_channels = params.get("input_channels", 3)
        self.vanilla = VanillaBlock(in_channels, VANILLA_FILTERS, dropout=dropout)

        blocks, in_ch, alpha_in = [], VANILLA_FILTERS[-1], 0.0
        for k in range(0, len(OCTAVE_FILTERS), 2):
            blocks.append(OctaveBlock(in_ch, alpha_in, k, k + 1, dropout=dropout))
            in_ch, alpha_in = OCTAVE_FILTERS[k + 1], OCTAVE_ALPHA[k + 1]
        self.octave = ModuleList(blocks)
        self.dsc = DSCBlockGated(OCTAVE_FILTERS[-1], DSC_FILTERS, dropout=dropout,
                                 gate_mode=params.get("dancer_gate_mode", "full"))

    def forward(self, x):
        x = self.vanilla(x)
        for block in self.octave:
            x = block(x)
        if isinstance(x, tuple):                       # only if the last alpha were non-zero
            high, low = x
            x = high + F.interpolate(low, size=high.shape[-2:], mode="bilinear", align_corners=False)
        return self.dsc(x)


if __name__ == "__main__":                              # quick manual check
    enc = DANCER_Encoder({"dropout": 0.5, "input_channels": 3})
    n = sum(p.numel() for p in enc.parameters())
    y = enc(torch.randn(1, 3, 320, 480))
    print("params {:.3f} M | output {}".format(n / 1e6, tuple(y.shape)))
